#!/bin/bash

# Test Script: Verify Real-Time Reactions

echo "🧪 Testing Real-Time Message Reactions"
echo "======================================="

echo ""
echo "📋 Test Instructions:"
echo "1. Start your backend server: cd backend && go run main.go"
echo "2. Start your frontend: cd frontend && npm run dev"
echo "3. Open two browser windows/tabs with different users"
echo "4. Follow the test steps below"

echo ""
echo "🔧 Test Steps:"
echo ""

echo "Step 1: Send Test Messages"
echo "-------------------------"
echo "User A: Send 'Message 1: React to this! 😊'"
echo "User B: Send 'Message 2: And this one too! 🎉'"
echo "User A: Send 'Message 3: Try multiple reactions'"

echo ""
echo "Step 2: Test Real-Time Reaction Adding"
echo "-------------------------------------"
echo "User A: Add reaction 👍 to User B's 'Message 2'"
echo "✅ Verify User B sees the 👍 reaction INSTANTLY"
echo ""
echo "User B: Add reaction ❤️ to User A's 'Message 1'"
echo "✅ Verify User A sees the ❤️ reaction INSTANTLY"
echo ""
echo "User A: Add reaction 😂 to their own 'Message 3'"
echo "✅ Verify User B sees the 😂 reaction INSTANTLY"

echo ""
echo "Step 3: Test Multiple Reactions"
echo "-------------------------------"
echo "User B: Add reaction 👍 to User A's 'Message 3'"
echo "User A: Add reaction 🎉 to User A's 'Message 3'"
echo "✅ Verify both users see: 😂👍🎉 with correct counts"

echo ""
echo "Step 4: Test Real-Time Reaction Removal"
echo "----------------------------------------"
echo "User A: Remove their 👍 reaction from User B's 'Message 2'"
echo "✅ Verify User B sees the 👍 reaction disappear INSTANTLY"
echo ""
echo "User B: Remove their ❤️ reaction from User A's 'Message 1'"  
echo "✅ Verify User A sees the ❤️ reaction disappear INSTANTLY"

echo ""
echo "Step 5: Test Page Refresh Persistence"
echo "-------------------------------------"
echo "User A: Refresh the page (F5 or Ctrl+R)"
echo "User B: Refresh the page (F5 or Ctrl+R)"
echo "✅ Verify all remaining reactions are still visible after refresh"

echo ""
echo "✅ Expected Real-Time Behavior:"
echo "------------------------------"
echo "• Reactions appear INSTANTLY without refresh"
echo "• Reaction counts update in real-time"
echo "• Multiple users can react to same message"
echo "• Removing reactions updates immediately"
echo "• Same reaction from different users shows correct count"
echo "• Users can react to their own messages"
echo "• Reactions persist after page refresh"

echo ""
echo "❌ If reactions don't appear in real-time:"
echo "-----------------------------------------"
echo "Check these potential issues:"
echo "1. WebSocket connection status in browser console"
echo "2. Backend WebSocket broadcasting logs"
echo "3. Frontend reaction event handling"
echo "4. API response timing"

echo ""
echo "🔍 Debugging Commands:"
echo "---------------------"
echo "Frontend Console:"
echo "• Check for 'Sending reaction:' log messages"
echo "• Look for WebSocket message received logs"
echo "• Verify no JavaScript errors"
echo ""
echo "Backend Console:"
echo "• Should see reaction add/remove API calls"
echo "• Should see WebSocket broadcast messages"
echo ""
echo "Network Tab:"
echo "• POST /message/reaction/add should return 200"
echo "• POST /message/reaction/remove should return 200"

echo ""
echo "🎯 Success Criteria:"
echo "-------------------"
echo "✅ Reactions appear instantly on both ends"
echo "✅ Reaction counts are accurate"
echo "✅ Multiple reactions work correctly"
echo "✅ Reaction removal works in real-time"
echo "✅ Reactions persist after refresh"
echo "✅ No duplicate or missing reactions"
echo "✅ WebSocket connection remains stable"
echo "✅ No console errors during testing"

echo ""
echo "🚀 Flow Verification:"
echo "--------------------"
echo "User A clicks reaction → API updates DB → Backend broadcasts WebSocket → User B sees reaction instantly"

echo ""
echo "Ready to test real-time reactions! 🎬"
