#!/bin/bash

# Test Script: Verify Deleted Messages Persist After Refresh

echo "🧪 Testing Deleted Message Persistence After Refresh"
echo "=================================================="

echo ""
echo "📋 Test Instructions:"
echo "1. Start your backend server: cd backend && go run main.go"
echo "2. Start your frontend: cd frontend && npm run dev"
echo "3. Open two browser windows/tabs with different users"
echo "4. Follow the test steps below"

echo ""
echo "🔧 Test Steps:"
echo ""

echo "Step 1: Send Test Messages"
echo "-------------------------"
echo "User A: Send 'Message 1: This will stay'"
echo "User B: Send 'Message 2: Hello back!'"
echo "User A: Send 'Message 3: This will be deleted'"
echo "User B: Send 'Message 4: Another message'"

echo ""
echo "Step 2: Delete a Message"
echo "------------------------"
echo "User A: Delete 'Message 3: This will be deleted'"
echo "✅ Verify both users see: 🗑️ 'You/This message was deleted'"

echo ""
echo "Step 3: Test Refresh (MAIN TEST)"
echo "--------------------------------"
echo "User A: Refresh the page (F5 or Ctrl+R)"
echo "User B: Refresh the page (F5 or Ctrl+R)"

echo ""
echo "✅ Expected Results After Refresh:"
echo "----------------------------------"
echo "Both users should see:"
echo "📝 Message 1: This will stay"
echo "📝 Message 2: Hello back!"
echo "🗑️ You deleted this message / This message was deleted"
echo "📝 Message 4: Another message"

echo ""
echo "❌ If deleted message disappears after refresh:"
echo "----------------------------------------------"
echo "- Check backend logs for any filtering"
echo "- Check browser console for errors"
echo "- Verify database contains deleted: true messages"

echo ""
echo "🔍 Debugging Commands:"
echo "---------------------"
echo "Backend: Check MongoDB for deleted messages:"
echo "  db.messages.find({deleted: true})"
echo ""
echo "Frontend: Check API response:"
echo "  Network tab -> messages endpoint -> Response"
echo ""
echo "Browser: Check localStorage:"
echo "  localStorage.getItem('chat_history_[userId]_[roomId]')"

echo ""
echo "🎯 Success Criteria:"
echo "-------------------"
echo "✅ Deleted messages persist after page refresh"
echo "✅ Show proper placeholder text with trash icon"
echo "✅ Different text for sender vs receiver"
echo "✅ Same behavior in both browser windows"
echo "✅ No JavaScript errors in console"

echo ""
echo "🚀 Quick Fix Verification:"
echo "-------------------------"
echo "If the test passes, the following issues are resolved:"
echo "1. Backend includes deleted messages in API response"
echo "2. Frontend preserves 'deleted' property during message mapping"
echo "3. MessageBubble properly renders deleted message placeholders"
echo "4. LocalStorage caching doesn't interfere with deleted messages"

echo ""
echo "Ready to test! 🎬"
