#!/bin/bash

echo "🚫 ZERO-COUNT REACTION HIDING TEST"
echo "================================="
echo ""
echo "This test verifies that reactions with 0 count are properly hidden"
echo "from the UI and cleaned up from the database."
echo ""

echo "📋 SETUP:"
echo "1. Backend running: cd backend && go run main.go"
echo "2. Frontend running: cd frontend && npm run dev"
echo "3. Two browser tabs with different users logged in"
echo ""

echo "🧪 TEST SCENARIOS:"
echo ""

echo "Scenario 1: Single User Removes Own Reaction"
echo "-------------------------------------------"
echo "User A: Send message 'Test reaction removal'"
echo "User A: Add 👍 reaction to the message"
echo "✅ Expected: Message shows 👍(1) highlighted in blue"
echo ""
echo "User A: Click the 👍 reaction again to remove it"
echo "✅ Expected: 👍 reaction completely disappears (no 👍(0))"
echo "✅ Expected: No reaction bubbles shown under the message"
echo ""

echo "Scenario 2: Multiple Users, One Removes Reaction"
echo "-----------------------------------------------"
echo "User A: Add 👍 reaction to the message"
echo "User B: Add ❤️ reaction to the same message"
echo "✅ Expected: Message shows 👍(1) ❤️(1)"
echo ""
echo "User A: Remove their 👍 reaction"
echo "✅ Expected: Only ❤️(1) remains, 👍 completely gone"
echo "❌ Should NOT show: 👍(0) ❤️(1)"
echo ""

echo "Scenario 3: Switch Reactions (Zero Count Cleanup)"
echo "------------------------------------------------"
echo "User A: Add 😂 reaction"
echo "✅ Expected: ❤️(1) 😂(1) showing"
echo ""
echo "User B: Switch from ❤️ to 😂"
echo "✅ Expected: Only 😂(2) showing, ❤️ completely gone"
echo "❌ Should NOT show: ❤️(0) 😂(2)"
echo ""

echo "Scenario 4: All Users Remove Same Reaction"
echo "-----------------------------------------"
echo "User A: Add 👍 reaction"
echo "User B: Add 👍 reaction"
echo "✅ Expected: 👍(2) showing"
echo ""
echo "User A: Remove 👍 reaction"
echo "✅ Expected: 👍(1) showing"
echo ""
echo "User B: Remove 👍 reaction"
echo "✅ Expected: No reactions showing, 👍 completely gone"
echo "❌ Should NOT show: 👍(0)"
echo ""

echo "Scenario 5: Page Refresh After Removals"
echo "---------------------------------------"
echo "After all the above tests, refresh both browser tabs"
echo "✅ Expected: Only reactions with count > 0 appear"
echo "✅ Expected: No ghost reactions with 0 count"
echo ""

echo "🔍 DEBUGGING CHECKS:"
echo "===================="
echo ""
echo "1. Browser Console Verification:"
echo "   Open DevTools and check message objects:"
echo "   console.log('Message reactions:', allMessages.map(m => ({id: m.id, reactions: m.reactions})));"
echo ""
echo "   ✅ Should show: reactions: {\"😂\": [\"user1\", \"user2\"]}"
echo "   ❌ Should NOT show: reactions: {\"👍\": [], \"😂\": [\"user1\"]}"
echo ""

echo "2. Database Verification:"
echo "   curl 'http://localhost:8080/messages?room_id=YOUR_ROOM_ID'"
echo ""
echo "   ✅ Expected database format:"
echo "   \"reactions\": {\"😂\": [\"user1\", \"user2\"]}"
echo ""
echo "   ❌ Should NOT have empty arrays:"
echo "   \"reactions\": {\"👍\": [], \"😂\": [\"user1\"]}"
echo ""

echo "3. Network Traffic Check:"
echo "   In DevTools > Network, when removing reactions:"
echo "   ✅ Should see WebSocket 'remove' events"
echo "   ✅ Should see API calls to /message/reaction/remove"
echo ""

echo "🎯 VISUAL INDICATORS:"
echo "===================="
echo ""
echo "✅ CORRECT BEHAVIOR:"
echo "• Reactions disappear completely when count reaches 0"
echo "• Only active reactions (count > 0) are displayed"
echo "• Smooth fade-out animation when last user removes reaction"
echo "• Clean message appearance with no empty reaction bubbles"
echo ""
echo "❌ INCORRECT BEHAVIOR:"
echo "• Showing reaction bubbles with \"0\" count"
echo "• Empty reaction arrays in browser console"
echo "• Ghost reactions appearing after page refresh"
echo "• Reaction bubbles with no users but still visible"
echo ""

echo "⚡ REAL-TIME VERIFICATION:"
echo "========================="
echo ""
echo "1. User A removes reaction → Should disappear immediately on User B's screen"
echo "2. Last user removes reaction → Should disappear on all screens simultaneously"
echo "3. No flickering or temporary \"0\" counts during transitions"
echo ""

echo "🐛 COMMON ISSUES TO WATCH FOR:"
echo "=============================="
echo ""
echo "Issue 1: Reaction shows as \"👍(0)\""
echo "Fix: Check frontend filter logic and backend cleanup"
echo ""
echo "Issue 2: Empty arrays in database"
echo "Fix: Verify backend RemoveReaction cleanup logic"
echo ""
echo "Issue 3: Ghost reactions after refresh"
echo "Fix: Check API response format and frontend data processing"
echo ""

echo "🚀 SUCCESS CRITERIA:"
echo "==================="
echo "✅ No reactions with 0 count displayed"
echo "✅ Empty reaction arrays removed from database"
echo "✅ Clean UI with only active reactions"
echo "✅ Proper real-time updates across all users"
echo "✅ Consistent behavior after page refresh"
echo ""

echo "Ready to test zero-count reaction hiding! 🎬"
echo ""
echo "💡 Quick Test Command:"
echo "Add reaction → Remove reaction → Verify it disappears completely"
